### DISCUSSION TITLE
Using an existing ServiceAccount with Headlamp Helm chart

### DISCUSSION THREAD

**Discussion by imacq** [kubernetes-sigs/headlamp#2986] [General]
# Using an existing ServiceAccount with Headlamp Helm chart

## Issue

When deploying Headlamp in environments where ServiceAccounts and RBAC are managed externally (e.g., through a platform team or GitOps process), I need to configure Headlamp to use an existing ServiceAccount instead of creating a new one.

## Current configuration

The Headlamp Helm chart creates a new ServiceAccount by default:

```yaml
serviceAccount:
  create: true
  annotations: {}
  name: ""
```

And it also creates a ClusterRoleBinding to grant the ServiceAccount access:

```yaml
clusterRoleBinding:
  create: true
  clusterRoleName: a-support
  annotations: {}
```

## Desired configuration

I want to use an existing ServiceAccount (e.g., `a-support`) that already has appropriate RBAC bindings.

## Questions

1. Is this the recommended approach for using existing ServiceAccounts with Headlamp?
