### DISCUSSION TITLE
Headlamp plugins using helm chart

### DISCUSSION THREAD

**Discussion by mtotone** [kubernetes-sigs/headlamp#3453] [Q&A] [answered]
Hello everyone,

I installed Headlamp on a Kubernetes cluster using the Helm chart.

Starting from version 0.31.0, it's possible to manage plugins using the pluginsManager field ([ref](https://github.com/kubernetes-sigs/headlamp/blob/main/charts/headlamp/values.yaml#L235)).

I added the following values:

```
pluginsManager:
  enabled: true
  configContent: |
    plugins:
      - name: cert-manager
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
        version: 0.1.0
      - name: trivy
        source: https://artifacthub.io/packages/headlamp/headlamp-trivy/headlamp_trivy
        version: 0.3.1
    installOptions:
      parallel: true
      maxConcurrent: 2
```

In the plugin installer container logs, I see:

```
info: Installing plugins from config: /config/plugin.yml
1 of 2 (cert-manager): info: Installing plugin cert-manager
1 of 2 (cert-manager): info: Fetching Plugin Metadata
2 of 2 (trivy): info: Installing plugin trivy
2 of 2 (trivy): info: Fetching Plugin Metadata
1 of 2 (cert-manager): info: Plugin Metadata Fetched
1 of 2 (cert-manager): info: Downloading Plugin
2 of 2 (trivy): info: Plugin Metadata Fetched
2 of 2 (trivy): info: Downloading Plugin
2 of 2 (trivy): info: Plugin Downloaded
2 of 2 (trivy): info: Extracting Plugin
2 of 2 (trivy): info: Plugin Extracted
Moved directory from /tmp/headlamp-plugin-temp-aMAAAo/headlamp_trivy to /headlamp/plugins/headlamp_trivy
2 of 2 (trivy): success: Plugin Installed
2 of 2 (trivy): success: Plugin installed successfully
1 of 2 (cert-manager): info: Plugin Downloaded
1 of 2 (cert-manager): info: Extracting Plugin
1 of 2 (cert-manager): info: Plugin Extracted
Moved directory from /tmp/headlamp-plugin-temp-kIOIjn/headlamp_cert-manager to /headlamp/plugins/headlamp_cert-manager
1 of 2 (cert-manager): success: Plugin Installed
1 of 2 (cert-manager): success: Plugin installed successfully
info: Bulk installation completed: {"total":2,"failed":0,"skipped":0,"successful":2}
Watching /config/plugin.yml for changes...
```

However, in the web UI, no plugins appear.

Has anyone successfully gotten plugins to work using the Helm chart? Am I missing something?

Thanks.
