### ISSUE TITLE
Flatpak: cannot execute `aws eks get-token`

### ISSUE THREAD

**Issue by gtirloni** [kubernetes-sigs/headlamp#1582]
In order to access the Kubernetes API of an EKS cluster, it's necessary to use the `aws eks get-token` command.

This is usually configured in the kubeconfig file:

```yaml
- name: eks_my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      command: aws
      env:
      - name: AWS_PROFILE
        value: my-profile
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

However, the Flatpak does not have access to the host's filesystem by default. This can be granted with `filesystem=host` but there are other issues.

The awscli executable is installed in `/usr/bin/aws` on the host but `/usr/bin` inside the Flatpak is different. To access the host's awscli one has to execute `/var/run/host/usr/bin/aws`, so adding `/var/run/host/usr/bin` to the PATH inside the Flatpak is necessary. But there are other issues.

The awscli tool is a Python application that loads other Python modules. The Python interpreter won't be able to find the host's dist-packages directory. It's necessary to add `/var/run/host/usr/lib/python3/dist-packages` to the `PYTHONPATH` environment variable inside the Flatpak. But there are other issues.

The awscli tool uses a native module called `awscrt` that is compiled for Python 3.11 but the Flatpak packages Python 3.10. When the interpreter tries to load `awscli.checksums`, it does not have permission to write to the `__pycache__` directory:

```
$ python -v
>>> import awscrt.checksums
# code object from /var/run/host/usr/lib/python3/dist-packages/awscrt/__init__.py
# could not create '/var/run/host/usr/lib/python3/dist-packages/awscrt/__pycache__/__init__.cpython-310.pyc': PermissionError(13, 'Permission denied')
```

Setting `PYTHONDONTWRITEBYTECODE=1` resolves the error but the module still can't be loaded (probably related to the binary .so that needs to be loaded).

It seems a better solution would be for Headlamp to pack all the tools required to authenticate to EKS/AKS/GKE into the Flatpak.
