### ISSUE TITLE
OIDC: No permissions to list pods (dex + eks)

### ISSUE THREAD

**Issue by batbattur** [kubernetes-sigs/headlamp#1651]
## Description
OIDC: No permissions to list pods. Similar to https://github.com/headlamp-k8s/headlamp/issues/393 and https://github.com/headlamp-k8s/headlamp/issues/1436

## Impact
Cannot use headlamp after OIDC login

## Environment and steps to reproduce
Set-up:

1. on EKS, deployed headlamp

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        name: headlamp
        kind: HelmRepository
        namespace: headlamp
  values:
    config:
      oidc:
        baseURL: https://headlamp.someurl.com
        clientID: headlamp
        clientSecret: somesecret
        issuerURL: "https://dex.someurl.com"
        scopes: "openid email profile groups"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: headlamp.someurl.com
          paths:
            - path: /
              type: Prefix
```

2. Setup Dex with Github connector:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: dex
      interval: 1m
  values:
    image:
      tag: v2.31.0
    config:
      issuer: https://dex.someurl.com
      storage:
        type: memory
      oauth2:
        responseTypes: ["code", "token", "id_token"]
      staticClients:
      - name: 'Headlamp'
        id: headlamp
        secret: somesecret
        redirectURIs:
        - 'https://headlamp.someurl.com/oidc-callback'
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: github-app-client-id
          clientSecret: github-client-secret
          redirectURI: https://dex.someurl.com/callback
          orgs:
          - name: someorg
            teams:
            - somegroup
    ingress:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: dex.someurl.com
          paths:
          - path: /
            pathType: Prefix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-cluster-auth
subjects:
- kind: Group
  name: someorg:somegroup
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: read-only
```

3. Then configure OIDC Provider for Amazon EKS:

<img width="862" alt="Screen Shot 2024-01-09 at 7 22 30 PM" src="https://github.com/headlamp-k8s/headlamp/assets/58952979/d562e201-02b4-48d6-b320-e7dac35d91a6">

4. Then confirmed that logging in through github oauth successfully returns the jwt token (decoded):
```
{
  "iss": "https://dex.someurl.com",
  "sub": "redacted",
  "aud": "headlamp",
  "exp": 1704941501,
  "iat": 1704855101,
  "at_hash": "redacted",
  "c_hash": "redacted",
  "email": "redacted",
  "email_verified": true,
  "groups": [
    "someorg:somegroup"
  ],
  "name": "redacted",
  "preferred_username": "redacted"
}
```
 
5. Then the `No permissions to list pods` error shows up.
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "events is forbidden: User \"system:anonymous\" cannot list resource \"events\" in API group \"\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "kind": "events"
  },
  "code": 403
}
```

## Expected behavior
Expected to see cluster details

## Additional information
What else should be configured? Any help would be appreciated!

**Comment by batbattur** [comment]
Also noted that the `headlamp-admin` token doesn't get generated if the OIDC config is set in headlamp.

**Comment by batbattur** [comment]
We confirmed that our external dex is working with argocd using https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#existing-oidc-provider so it seems like there's an issue with headlamp.

**Comment by yolossn** [comment]
@batbattur From the response that you have received from the Kubernetes API server (403 Response) looks like you might be missing the Cluster Role binding. Please refer this [link](https://github.com/headlamp-k8s/headlamp/blob/main/docs/installation/keycloak/keycloak-minikube.md#configuring-a-clusterrole-binding-for-the-oidc-user) for creating a cluster role binding for your group. I think this should help solve the problem.

**Comment by batbattur** [comment]
In our dex connector, we have github with the following config that allows `<someorg>:<somegroup>` login:
```
          orgs:
          - name: someorg
            teams:
            - somegroup
```

Then we have the following Cluster Role binding for the `someorg:somegroup` which binds read-only permissions to it.

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-cluster-auth
subjects:
- kind: Group
  name: someorg:somegroup
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: read-only
```

I thought this should do it. Or does it specifically need a `cluster-admin` role?

<hr>


> User \"system:anonymous\" cannot list resource \"events\" in API group \"\" at the cluster scope

Does `system:anonymous` mean that it couldn't detect the logged-in user belonging to the github group?
