### ISSUE TITLE
Loading chunk failed

### ISSUE THREAD

**Issue by remram44** [kubernetes-sigs/headlamp#1724]
It seems there is something wrong with routing, I get this error:

> `Uncaught SyntaxError: expected expression, got '<'`
> `Uncaught (in promise) ChunkLoadError: Loading chunk 5466 failed.
(missing: https://headlamp.mydomain/c/main/static/js/5466.f19aafa7.chunk.js)`

As you can see it is loading this JS file from the wrong path, gets HTML instead.

**Comment by remram44** [comment]
Installed with Helm using ingress.enabled=true (but I see the same error over `kubectl port-forward` rather than the ingress)

That's chart version 0.18.2 appVersion 0.22.0

```yaml
config:
  oidc:
    clientID: REDACTED
    clientSecret: REDACTED
    issuerURL: REDACTED
    secret:
      create: true
      name: oidc
ingress:
  annotations:
    haproxy.org/forwarded-for: "true"
    haproxy.org/ssl-redirect: "true"
    haproxy.org/ssl-redirect-code: "301"
  enabled: true
  hosts:
  - host: k8s-headlamp.redacted.example.com
    paths:
    - path: /
      type: Prefix
```

This also happens in a clean, new GKE standard cluster with default configuration and helm with no config set at all:

`helm install headlamp headlamp/headlamp --namespace headlamp --create-namespace`
