### ISSUE TITLE
Helm Chart has "persistentVolumeClaim" but it does nothing

### ISSUE THREAD

**Issue by remram44** [kubernetes-sigs/headlamp#1725]
Setting `persistentVolumeClaim.enabled` to true creates a PVC but it is not used for anything.

**Comment by knrt10** [comment]
Hi @remram44. PVC's when enabled can be used for mounting the plugins folder. You have to specify the volume in `values.yaml` as well for PVC to bound with headlamp deployment. 

```yaml
volumes:
  - name: example-volume
    # Define your volume type and its attributes
    persistentVolumeClaim:
      claimName: your-pvc-name  # This should match the name of the PersistentVolumeClaim you created
 ```

Does this answer your question?
