### ISSUE TITLE
Create Flux plugin

### ISSUE THREAD

**Issue by joaquimrocha** [kubernetes-sigs/headlamp#1872]
A Flux plugin would be very useful for all users of flux who would like a UI for it and who could also benefit from having it integrated in a generic K8s UI like Headlamp.

**Comment by ashu8912** [comment]
The progress on this is tracked here https://github.com/headlamp-k8s/plugins/pull/75

The plugin should look for Flux installation on the Cluster and show different views related to Flux.

- [x] Application List View is Done
- [x] Application Detail View Lists basic detail about a Kustomization or a HelmRelease
- [x] Application Detail View has Sync With Source and Sync Without Source action buttons
- [x] Application Detail View has Suspend action button 
- [x] Application Detail View also lists The inventory and links them to the correct K8s resource view on Headlamp
- [x] Source List View is Done
- [x] Source Detail View shows basic detail About a GitRepository or  OCIRepository or Buckets or HelmRepos and HelmCharts
- [x] Source Detail View Allows suspending and resuming reconciliation
- [x] Notification List View is done
- [] Notification Detail View is done
- [x] Image Automation List View is done
- [x] Image Automation Detail View shows basic details for Image Repo or Image Policies or Image Update Automations
- [x] Flux Runtime View Lists all the flux related controllers and CRDs
- [ ] Flux Runtime shows the running version of flux

**Comment by kingdonb** [comment]
I've got this running in a cluster now:

<img width="1399" alt="Screenshot 2024-08-22 at 10 02 02 AM" src="https://github.com/user-attachments/assets/9af7b24d-2387-4122-a787-3783a468ff83">

looking good! I need to add some flux artifacts, there may be one or more possibilities for how to detect the Flux Runtime version. I am seeing a label on each of my controllers, for example:

```
  labels:
    app.kubernetes.io/component: helm-controller
    app.kubernetes.io/instance: cozy-fluxcd
    app.kubernetes.io/managed-by: flux-operator
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.3.0
    control-plane: controller
    fluxcd.controlplane.io/name: flux
    fluxcd.controlplane.io/namespace: cozy-fluxcd
```

This is a managed flux, via flux-operator, so this may differ (?) from how it looks on a flux installed via `flux boostrap` or `flux install` - need to double check
