### ISSUE TITLE
OIDC with Keycloak which is also in the cluster?

### ISSUE THREAD

**Issue by senpro-ingwersenk** [kubernetes-sigs/headlamp#1900]
Hello!

Discussions were disabled, so apologies for posting this as an issue. :)

Most of my company collegues aren't as terminal-savy as me and a former worker had demployed a k3s cluster here. Now I added Headlamp as a nice Web UI to give my collegue an entrypoint into the cluster so they can see what it is doing and the likes.

However, I had wanted to use our existing Keycloak OIDC structure, bound to our AD, to enable seamless SSO. And I can, in fact, click the login button and it "logs me in" - but the browser console tells me that I am unauthenticated.

Granted, I know that it is attempting to authenticate me directly with the API server through OIDC.

Question is, how can I realize that, without having to share a singular service account token around? I shared it with another collegue for now so they can try Headlamp out besides myself, but I would like to integrate it into our existing infrastructure.

Since the container has the service account loaded and a ClusterRoleBinding is established, Headlamp can authenticate with this just fine, in theory.

Is there anything I missed or that I have to do to make it work?

Here is the current deployment, in full:

<details>

<summary>Full deployment YAML</summary>

```yaml
## Copied and modified from source
## ref https://github.com/headlamp-k8s/headlamp/blob/main/kubernetes-headlamp.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      serviceAccountName: headlamp-sva
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:latest
        args:
          - "-in-cluster"
          - "-plugins-dir=/headlamp/plugins"
        ports:
        - name: http
          containerPort: 4466
          protocol: TCP
        env:
          - name: HEADLAMP_CONFIG_OIDC_CLIENT_ID
            value: "headlamp"
          - name: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
            value: "..."
          - name: HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL
            value: "https://keycloak.our.domain/realms/master"
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
      nodeSelector:
        'kubernetes.io/os': linux
---
kind: Secret
apiVersion: v1
metadata:
  name: headlamp-admin
  namespace: headlamp
  annotations:
    kubernetes.io/service-account.name: "headlamp-sva"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-sva
  namespace: headlamp
  labels:
    k8s-app: headlamp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
  namespace: headlamp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: headlamp-sva
  namespace: headlamp
---
kind: Service
apiVersion: v1
metadata:
  name: headlamp
  namespace: headlamp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4466
  selector:
    k8s-app: headlamp
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`headlamp.senpro.it`)
      services:
        - name: headlamp
          port: 80
```

</details>

Thanks and kind regards!
