### ISSUE TITLE
Unable to connect to cluster if kubeconfig context name doesn't match kubeconfig cluster name

### ISSUE THREAD

**Issue by omniproc** [kubernetes-sigs/headlamp#2132]
As the title suggests. Best explained with the following example.

Working example:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://kubernetes.local:6443
  name: my-cluster-name
contexts:
- context:
    cluster: my-cluster-name
    user: my-user-name
  name: my-cluster-name
current-context: my-cluster-name
kind: Config
preferences: {}
users:
- name: my-user-name
  user:
    client-certificate-data: xxx
    client-key-data: xxx
```

Failing example:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://kubernetes.local:6443
  name: my-cluster-name
contexts:
- context:
    cluster: my-cluster-name
    user: my-user-name
  name: my-context-name
current-context: my-context-name
kind: Config
preferences: {}
users:
- name: my-user-name
  user:
    client-certificate-data: xxx
    client-key-data: xxx
```

Looking at the dev console in Headlamp I can see 404 errors when Headlamp tries to reach `http://localhost:4466/clusters/my-context-name/version`, which probably is the root cause of this issue.

Worst thing about this issue is that if you load a "invalid" kubeconfig like that you'll have to delete Headlamps cache because as long as this error persists it's not possible to delete the failing kubeconfig in Headlamp (it will try to delete /my-context-name/ which does't exist).

Please note that while the context-name may match the cluster name it is pretty common that it doesn't and the kubeconfig spec doesn't make this mandatory at all.

Tested Headlamp versions: 0.24.0 and 0.24.1 on Windows.
