### ISSUE TITLE
Can't login with multiple .kube/config-* files. Authentication token required

### ISSUE THREAD

**Issue by levissfuture** [kubernetes-sigs/headlamp#2212]
I am trying to login to multiple clusters by adding different .kubeconfig files. Successful login only occurs on one cluster, which is the first one in the default kubeconfig file. In my case, it is a local cluster created by docker. In other cases, when trying to connect, it asks for an "authentication token", although it should let you in using the certificate that is in these files. How can I solve this problem? I want to log in to clusters using certificates.
![Screenshot 2024-07-29 151405](https://github.com/user-attachments/assets/8b83726f-406f-47d8-bd65-298922e9f2e1)

**Comment by joaquimrocha** [comment]
Maybe @ashu8912 can take a look.

**Comment by questionmark78** [comment]
Not sure if it is related, but in 0.25.0 on Mac I have similar issue.
I have 3 kubeconfigs loaded, but only one is showing (next to the default loading the docker-desktop).
I do see all three of them in the IndexedDB, as displayed in the screenshot.
<img width="1533" alt="Screenshot 2024-08-01 at 12 01 33" src="https://github.com/user-attachments/assets/0224983f-bee7-4ced-8305-baec75c68f74">

**Comment by joaquimrocha** [comment]
@questionmark78 , can you provide the values of those kubeconfigs in the kubeconfig store? (of course, redact whatever you need)

**Comment by questionmark78** [comment]
@joaquimrocha What information do you need exactly? The values of the kubeconfigs in the kubeconfig store contain the encoded values of my kubeconfig files, which are the files from DigitalOcean Kubernetes.
It all works fine in 0.24.1

Basically the kubeconfig files contain these information (modified as not to reveal details):

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tClNvbWUgY2VydGlmaWNhdGUgdmFsdWUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    server: https://my-uuid.k8s.ondigitalocean.com
  name: do-k8s-dev-01
contexts:
- context:
    cluster: do-k8s-dev-01
    user: do-k8s-dev-01-admin
  name: do-k8s-dev-01
current-context: do-k8s-dev-01
kind: Config
preferences: {}
users:
- name: do-k8s-dev-01-admin
  user:
    token: dop_v1_token
```
