### ISSUE TITLE
OIDC authentication is not handled in app

### ISSUE THREAD

**Issue by O5ten** [kubernetes-sigs/headlamp#2242]
I'm having trouble connecting to a cluster that has oidc configured as authentication method. Competing products (openlens) is opening a browser window to (re)authenticate to the cluster when needed. headlamp is just asking me for a service account token.  

![image](https://github.com/user-attachments/assets/784c8d8f-e084-4fdc-bae8-83eb6618cc9b)

This is a sample of my .kube/config
```yaml
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://login.microsoftonline.com/<tenant>/v2.0
      - --oidc-client-id=<some-client-id>
      - --oidc-client-secret=<some-client-secret>
      command: kubectl
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
