### ISSUE TITLE
Headlamp k8s and pod security

### ISSUE THREAD

**Issue by devantler** [kubernetes-sigs/headlamp#2286]
Heyo,

I am using Talos Linux and have enforced restrictive pod security by default on all pods in my MachineConfig:

```yaml
cluster:
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            audit: restricted
            audit-version: latest
            enforce: baseline
            enforce-version: latest
            warn: restricted
            warn-version: latest
          kind: PodSecurityConfiguration
```

What is the minimum needed pod security for Headlamp to operate correctly? Right now I have it set to:

```txt
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
```

Which works, and I can list everything needed. But I am curious if I can configure this to be a bit more restricted, such that the Headlamp app does not have privileged permissions.
