### ISSUE TITLE
"Show logs" and "Exec into Pod" do not work with Clusters via Rancher

### ISSUE THREAD

**Issue by mfriess2** [kubernetes-sigs/headlamp#2300]
Hello,

I'm using Headlamp 0.25.1 (0.24.x had the same problems) as MacOS Desktop App and when I try to view the logs of any pod, it does not show them. The popup stays black and after 1 or 2 seconds the "reconnect" button shows up: 

![image](https://github.com/user-attachments/assets/c81d4099-a6fb-4a84-a7ff-d528aa91d155)

All the buttons have no effect, the logs don't show up.
I can see the logs and do exec-into via "kubectl" (= my permissions are fine).
I can also see logs and exec-into with OpenLens.
The problem is there for all pods and in all my different clusters.

And I have the same problem with the "exec into pod" button. I can see that it tries out several different shells ("Trying to run "/bin/sh"…") but at the end it fails with:
```
Failed to connect…

Press the enter key to reconnect.
```

**Comment by ashu8912** [comment]
Hii @mfriess2 I tried this on mac but it seems to work for me, what mac model are you on?? I tried this on a silicon chip.

<img width="1689" alt="Screenshot 2024-09-17 at 12 44 46 PM" src="https://github.com/user-attachments/assets/511fcebc-252b-
<img width="1677" alt="Screenshot 2024-09-17 at 12 43 15 PM" src="https://github.com/user-attachments/assets/71845df4-f8d6-40e8-8aa3-6debd0522e62">
40ed-80e0-e0e3223d6bdc">

**Comment by mfriess2** [comment]
Thanks for taking the time! I re-tested too and found out that it works for some clusters but for some not.
Maybe it's related to "private network access" or to access via Rancher or to a VPN client.
I will try to narrow it down and let you know!

**Comment by mfriess2** [comment]
Hello,

I think I found the missing peace of the puzzle.

I tested two cases with the exact same cluster:
* direct connection to the cluster (with the kube-admin config from the control-plane node) => Logs and Exec work
* connection via Rancher => Logs and Exec do NOT work

In both cases, the pods are listed and shown. And "kubectl exec/logs" also works for both ways meaning that there is no permission problem. And it is also not working on Windows, not just MacOS! Shall I adapt the issue title?

So what special thing is happening in the background that show-logs and exec-into does not work via Rancher?

Here are examples of both ways in the kubeconfig:
```
clusters:
- cluster:
  name: rancher-access
    server: https://rancher.example.com/k8s/clusters/a-b-abcd45e

- cluster:
  name: direct-access
    server: https://1.2.3.4:6443
    certificate-authority-data: LS0t...

users:
- name: rancher-access-user
  user:
    token: kubeconfig-u-<values>:<values>

- name: direct-access-user
  user:
    client-certificate-data: LS0t...
    client-key-data: LS0t...
```
