### ISSUE TITLE
Authorization OIDC and id-token (Windows Desktop)

### ISSUE THREAD

**Issue by CypressMan** [kubernetes-sigs/headlamp#2398]
I have kubeconfig that works through kubectl and Lens. It looks like this:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0...
    server: https://api.k8s:6443
  name: k8s
contexts:
- context:
    cluster: k8s
    user: USER_ID@k8s
  name: k8s
current-context: k8s
kind: Config
preferences: {}
users:
- name:USER_ID@k8s
  user:
    auth-provider:
      config:
        client-id: okd_dev
        client-secret: sfgsfgsfgsfg
        id-token: sfgsgsfg
        idp-issuer-url: https://keycloak-k8s.com
        refresh-token: gsfgsfgsfg
```
When adding kubeconfig to the HeadLamp (Windows Desktop), the program asks for an **id-token**. I prescribe it exactly the same as in kubeconfig. Please, is it possible to make it so that he does not ask for the **id-token**, but takes it from the kubeconfig?
