### ISSUE TITLE
Setup Okta(OIDC) with Headlamp

### ISSUE THREAD

**Issue by SimonHope** [kubernetes-sigs/headlamp#2470]
## Describe the bug
Hello. I'm trying to integrate Okta(OIDC) with Headlamp follow with this document https://headlamp.dev/docs/latest/installation/in-cluster/oidc. But it doesn't work :( (I have already done clusterRole and clusterRoleBlinding)

Here my error
![image](https://github.com/user-attachments/assets/3695ed97-3c26-4793-9eef-b020d5415940)

## To Reproduce
Steps to reproduce the bug:
1. Open Headlamp URL
2. Sign in
3. See error

## Environment (please provide info about your environment):
 - Installation type: EKS version 1.30
 - Headlamp Version: Latest
 - Okta: Version 2024.10.0 E

Headlamp.yaml
```
kind: Service
apiVersion: v1
metadata:
  name: headlamp
  namespace: devops
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
    - port: 80
      targetPort: 4466
  selector:
    k8s-app: headlamp
  type: LoadBalancer

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      serviceAccountName: headlamp-admin
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:latest
        args:
          - "-in-cluster"
          - "-plugins-dir=/headlamp/plugins"
          # Check if externalSecret is disabled
          # Check if clientID is non empty either from env or oidc.config
          - "-oidc-client-id=$(OIDC_CLIENT_ID)"
          # Check if clientSecret is non empty either from env or oidc.config
          - "-oidc-client-secret=$(OIDC_CLIENT_SECRET)"
          # Check if issuerURL is non empty either from env or oidc.config
          - "-oidc-idp-issuer-url=$(OIDC_ISSUER_URL)"
          # Check if scopes are non empty either from env or oidc.config
          - "-oidc-scopes=$(OIDC_SCOPES)"
        ports:
        - containerPort: 4466
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
        env:
        - name: OIDC_CLIENT_ID
          value: "values"
        - name: OIDC_CLIENT_SECRET
          value: "values"
        - name: OIDC_ISSUER_URL
          value: "values"
        - name: OIDC_SCOPES
          value: "values"
        volumeMounts:
        - name: kubeconfig-volume
          mountPath: /home/headlamp/.config/Headlamp/kubeconfigs/
          readOnly: true
      nodeSelector:
        'kubernetes.io/os': linux
      volumes:
      - name: kubeconfig-volume
        configMap:
          name: kubeconfig-configmap

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-clusterrolebinding
subjects:
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
  namespace: devops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: headlamp-admin
  namespace: devops
```

## Are you able to fix this issue?
[No.]
> Do you want to help fix this issue? Please see our [contribution docs](https://headlamp.dev/docs/latest/contributing). For any non-trivial contributions, we advise you to join our [our slack channel](https://kubernetes.slack.com/messages/headlamp) to discuss the implementation with Headlamp's core developers.

## Additional Context
[If needed, add any other info or screenshots about the bug here.]
[Is it a regression? What version of Headlamp did not have this bug?]
