### ISSUE TITLE
Filtering/searching by pod labels

### ISSUE THREAD

**Issue by illume** [kubernetes-sigs/headlamp#2547]
People put labels on things, and it would be good to use the labels.

## Describe the solution you'd like

Searching or filtering with labels.

Ideally filtering AND global search would work with labels.

- [x] filtering by labels in search
- [ ] filtering by labels in list view

## What users will benefit from this feature?

All the people who use labels. I think lots of people use labels (most?).

## Additional context

- Requested in a [slack thread](https://kubernetes.slack.com/archives/C01FXB5E8ER/p1730995623614169).
- This is one of the top requested features for Kubernetes dashboard: https://github.com/kubernetes/dashboard/issues/3160
- This was also requested by a user in person.

Similar to kubectl (see [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api) for reference).

For example, here's a manifest for a Pod that has two labels environment: production and app: nginx:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

`kubectl get pods -l environment=production`
