### ISSUE TITLE
Create Plugin Installer Container for Headlamp

### ISSUE THREAD

**Issue by knrt10** [kubernetes-sigs/headlamp#2787]
## Background

Headlamp currently supports plugin installation through the `headlamp-plugin` CLI tool, which can install plugins to a specified directory. However, for in-cluster mode deployments, we need a more Kubernetes-native way to manage plugins that can:
1. Install plugins during container initialization
2. Support configuration management
3. Handle plugin updates and removals
4. Work seamlessly with Kubernetes deployments

## Objective

Create a containerized version of the headlamp-plugin CLI tool that can be used as an init container in Kubernetes deployments. This container will:

- Accept a configuration file (via ConfigMap/Secret/Path) specifying which plugins to install
- Install the specified plugins into a shared volume before Headlamp starts
- Be automatically built and published as part of Headlamp's release process
- Provide a seamless way to manage plugins in Kubernetes environments

The container will be used in Headlamp's Helm chart as an init container, allowing operators to declaratively manage their plugins through Kubernetes-native configuration. This eliminates the need for manual plugin installation and ensures consistent plugin deployment across all Headlamp instances.

#### 1.1 Configuration Format
Create a YAML-based plugin configuration format:

```yaml
plugins:
- name: my-plugin
source: https://example.com/plugin.tar.gz
version: 1.0.0
config:
  key1: value1
  key2: value2
- name: another-plugin
source: https://github.com/org/plugin/releases/download/v1.0.0/plugin.tar.gz
version: latest
```

#### 2.1 New CLI Arguments
Extend headlamp-plugin to support:

```bash
headlamp-plugin install --config /path/to/config.yaml
headlamp-plugin install --source url --config-json '{"key": "value"}'
```

#### 2.2 Configuration Management
- Add configuration parsing functionality
- Support multiple plugin installations
- Enable plugin-specific configuration
- Add validation for configurations

#### 3.1 Init Container Setup
Update Headlamp's Helm chart to support plugin installation:

```yaml
initContainers:
- name: plugin-installer
image: headlamp/plugin-installer:latest
volumeMounts:
  - name: plugins-dir
   mountPath: /plugins
  - name: plugin-config
   mountPath: /config
env:
  - name: PLUGIN_CONFIG_PATH
   value: /config/plugins.yaml
volumes:
- name: plugins-dir
emptyDir: {}
- name: plugin-config
configMap:
  name: headlamp-plugin-config
```

#### 3.2 ConfigMap for Plugin Configuration
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: headlamp-plugin-config
data:
plugins.yaml: |
plugins:
  - name: my-plugin
   source: https://example.com/plugin.tar.gz
   version: 1.0.0
```

#### 4.1 Extend Plugin Manager
- Add configuration file support to PluginManager class
- Implement batch installation functionality
- Add configuration validation
- Support plugin-specific settings

#### 4.2 Create Docker Image
- Set up Docker build process
- Create installation scripts
- Add configuration parsing
- Include necessary dependencies

#### 4.3 Update Helm Chart
- Add init container configuration
- Create ConfigMap templates
- Add volume management
- Update documentation

#### 4.4 Add CI/CD Support
- Automate Docker image builds
- Add image versioning
- Set up container scanning
- Configure release automation

#### 5.1 Container Startup

```bash
#!/bin/sh
# Read config file
CONFIG_FILE=${PLUGIN_CONFIG_PATH:-/config/plugins.yaml}

# Parse and install plugins
headlamp-plugin install --config $CONFIG_FILE
```

#### 5.2 Volume Management
- Use emptyDir for single-node setups
- Support PersistentVolume for production
- Handle plugin updates
- Manage plugin configurations

## Success Criteria
- Plugins can be installed via configuration files
- Init container successfully installs plugins during pod startup
- Plugin configurations are properly managed
- Updates and removals work as expected
- Process is documented and maintainable

## Technical Requirements
- Kubernetes 1.16+
- Helm 3+
- Node.js 18+
- Access to plugin repositories
- Sufficient storage for plugins

## Notes
- Consider security implications of plugin downloads
- Plan for plugin version compatibility
- Document upgrade procedures
- Consider backup and restore procedures
- Add monitoring for plugin installation status

cc @headlamp-k8s/maintainers

**Comment by adwait-godbole** [comment]
Hi @knrt10. Thanks for bringing up this project in LFX. Are there any pre-tests for the selection criteria of mentees?

**Comment by vickybesra** [comment]
Dear @knrt10 , I hope you’re doing well. I’m writing to express my keen interest in the containerized headlamp-plugin CLI project for LFX Term 1, as I’m excited by the challenge of creating a Kubernetes-native solution that automates plugin installation during container initialization while managing configurations and updates seamlessly through Helm and ConfigMaps; my background in Kubernetes, container orchestration, and CI/CD has prepared me to tackle this project, and I’m eager to contribute my skills in developing, testing, and documenting a robust solution that enhances in-cluster plugin management for Headlamp—please let me know if I may take on this opportunity under your guidance.

**Comment by knrt10** [comment]
Hello folks, happy to see you interested in the issue. Please feel free to apply on the [LFX website](https://mentorship.lfx.linuxfoundation.org/project/992fc67e-ff9e-41fd-8062-28ec8733903f) with your proposal. Thanks

**Comment by illume** [comment]
@adwait-godbole wrote:

> Thanks for bringing up this project in LFX. Are there any pre-tests for the selection criteria of mentees?

Good question. The application is a cover letter and a resume. Applications for this project through https://mentorship.lfx.linuxfoundation.org/project/992fc67e-ff9e-41fd-8062-28ec8733903f

There's no pre-tests.

There's these two other Headlamp projects that are part of the mentorship program:
- https://github.com/headlamp-k8s/headlamp/issues/2791
- https://github.com/headlamp-k8s/headlamp/issues/2799

**Comment by mgalesloot** [comment]
An alternative approach. Usable today already. Works great with GitOps and Renovate. 

Note the ultimate solution should be based on OCI Artifacts as K8s Volumes. This is since v1.31 in alpha, so we have to wait for GA a bit. See https://kubernetes.io/blog/2024/08/16/kubernetes-1-31-image-volume-source/.

- Container Image
Plugins build a container image in their CICD. The container image will have the main.js and package.json and a minimal OS. Version the container image properly. 
- InitContainer
In the Headlamp installation, we can now make an initContainer for each plugin: 
```
- command:
     - /bin/sh
     - -c
     - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
  image: ghcr.io/kubebeam/kubescape-headlamp-plugin:latest ## you can specify a version such as 0.5.0-beta
  name: kubescape-plugin
  volumeMounts:
   - mountPath: /build/plugins
     name: headlamp-plugins
```
- emptyDir 
Put the plugin files on an emptydir. There is no point in making a PV for a few .js files. Also, a rolling update of the Headlamp would not like it when this PVC is ReadWriteOnce. There is no issue in putting a few filers in emptydir. 
````
volumes:
  - name: headlamp-plugins
    emptyDir: {}
````

- Helm Chart
In the headlamp helm chart we can add a list of plugins and let the helm template generate the initContainers. 
e.g.  
```
plugins: 
  - name: kubescape-plugin 
     image: ghcr.io/kubebeam/kubescape-headlamp-plugin:latest
  - name: flux
     image: ghcr.io/headlamp/plugins/flux:v1.0.0
```
