### ISSUE TITLE
I get redirected to OIDC auth pop up each time I click on any link/button inside headlamp UI. I'm using Azure AD for OIDC config. Headlamp installed in the cluster via helm

### ISSUE THREAD

**Issue by andreistefanzx** [kubernetes-sigs/headlamp#2848]
## Describe the bug
I get redirected to OIDC auth pop up each time I click on any link/button inside headlamp UI. I'm using Azure AD for OIDC config. Headlamp installed in the Google GKE cluster via helm

## To Reproduce
Steps to reproduce the bug:
1. Go to main page, click Sign In and go through OIDC auth
2. After authentication succeeds you can see the headlamp UI but if you click anything there, you'll get redirected to the OIDC auth screen again

Note: 

- I don't get any logs while going through the auth step or after that
- Logs from headlamp pod:
```
k logs -l app.kubernetes.io/name=headlamp -f           
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":342,"time":"2025-02-05T05:59:17Z","message":"Plugins dir: /headlamp/plugins"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":343,"time":"2025-02-05T05:59:17Z","message":"Dynamic clusters support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":344,"time":"2025-02-05T05:59:17Z","message":"Helm support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":345,"time":"2025-02-05T05:59:17Z","message":"Proxy URLs: []"}
{"level":"info","pluginPath":"/headlamp/plugins/lost+found/main.js","source":"/headlamp/backend/pkg/plugins/plugins.go","line":197,"error":"stat /headlamp/plugins/lost+found/main.js: permission denied","time":"2025-02-05T05:59:17Z","message":"Not including plugin path, main.js not found"}
{"level":"info","context":"main","clusterURL":"https://K8S_API_IP:443","source":"/headlamp/backend/pkg/kubeconfig/kubeconfig.go","line":315,"time":"2025-02-05T05:59:17Z","message":"Proxy setup"}
*** Headlamp Server ***
  API Routers:
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":399,"error":"error loading kubeconfig files: error reading kubeconfig file: open : no such file or directory","time":"2025-02-05T05:59:17Z","message":"loading kubeconfig"}
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":410,"error":"error loading kubeconfig files: error reading kubeconfig file: open /home/headlamp/.config/Headlamp/kubeconfigs/config: no such file or directory","time":"2025-02-05T05:59:17Z","message":"loading dynamic kubeconfig"}
```

![Image](https://github.com/user-attachments/assets/34b11931-0936-4891-892e-0de9b47b4c94)

- I get this in Chrome Inspect:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "nodes is forbidden: User \"system:anonymous\" cannot list resource \"nodes\" in API group \"\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "kind": "nodes"
  },
  "code": 403
}
```

## Environment (please provide info about your environment):
 - Installation type: helm deployment in GKE cluster
```
 # my helm value for OIDC
config:
      # -- base url path at which headlamp should run
      baseURL: ""
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: headlamp-oidc
      extraArgs: []
```
 - Headlamp Version: "0.28.0" helm chart

**Comment by tjbeckerGMI** [comment]
I am experiencing this same issue, running the same version inside of a cluster via helm, along with using Azure for OIDC auth.

Upon successfully authenticating in, it seems I have a split second to interact with the webpage and get it to load resources, but then I will lose access and get redirected to the sign in page

**Comment by yolossn** [comment]
Can you check if the `Authorization` header with Bearer token is sent to the requests made to the cluster.

Possibly Related
https://github.com/headlamp-k8s/headlamp/discussions/2850

**Comment by tjbeckerGMI** [comment]
This is @andreistefanzx ticket so don't want to hijack it but from my testing, in that brief moment where I do have access, I am seeing an Authorization header with the token in it, but then an error will pop up saying "Lost connection to the cluster", and I no longer see that header being sent in my next interaction with the UI

**Comment by yolossn** [comment]
@andreistefanzx is your GKE configured with Azure AD for OIDC auth?

**Comment by m3tzz** [comment]
I just had the same issues with @tjbeckerGMI  but I'm using Azure Entra ID for OIDC config with Headlamp installed in the OCI OKE cluster via FluxCD + Helm.

**Comment by imacq** [comment]
I have been facing this issue, any solution?

https://github.com/headlamp-k8s/headlamp/discussions/3036

**Comment by yashwanth-l** [comment]
I indeed have the same issue, as described in the title of this issue. Our environment is setup in Google, i.e., Headlamp is installed on GKE cluster via Flux(using helm)

```
config:
      baseURL: ""
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: headlamp-oidc
```

**Comment by nshttpd** [comment]
I've recently installed Headlamp into a GKE cluster with the Helm charts and am seeing the same issue. With the Token from the `headlamp` service account that's created and the ClusterRoleBinding for headlamp-admin to the cluster-admin Role for that ServiceAccount it works fine. When I AuthN via GCP OIDC and also have my User account `me@company.com` as a subject on the same ClusterRoleBinding it fails. 
 
When I look in the Google Log Explorer I do see in the `auditd` logs that my User account gets granted permissions to the K8S API for pod, node and other requests as I pull up the Headlamp dashboard because of the ClusterRoleBinding, but Headlamp itself responds with a 401. I've confirmed that the Bearer authorization header is sent and is valid.

I haven't dug through the backend code yet to see if there is any way to enable debug logs, but that's my next step to figure out why the K8S API seems to say the permission is granted, but headlamp things something is amiss.

**Comment by itpick** [comment]
also seeing 401s in my keycloak eks setup.  same issue and requesting a debug logging feature to help determine the cause: https://github.com/kubernetes-sigs/headlamp/issues/3576

**Comment by m3tzz** [comment]
Any news?
I can still login successfully, but I get a 401 error when click on nodes, pods, etc.? I'm currently using version 0.32.0, but it would be great to integrate my headlamp running on the EKS cluster with Azure Entra ID.


My current configuration is this one below

```
helmrelease

    config:
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: oidc
    envFrom:
      - secretRef:
          name: oidc
    env:
      - name: OIDC_CLIENT_ID
        value: "xxxx"
      - name: OIDC_ISSUER_URL
        value: "xxxx"
      - name: OIDC_SCOPES
        value: "openid,email,profile,GroupMember.Read.All,offline_access"
    extraArgs:
      - "--in-cluster"
      - "--plugins-dir=/headlamp/plugins"
      - "--oidc-client-id=$(OIDC_CLIENT_ID)"
      - "--oidc-idp-issuer-url=$(OIDC_ISSUER_URL)"
      - "--oidc-scopes=$(OIDC_SCOPES)"
      - "--oidc-client-secret=$(OIDC_CLIENT_SECRET)"
      - "--oidc-validator-client-id=$(OIDC_CLIENT_ID)"
      - "--oidc-validator-idp-issuer-url=$(OIDC_ISSUER_URL)"
      - "--oidc-groups-claim=groups"
      - "--oidc-validator-use-access-token=true"
```

```
---
# serviceaccount-viewer-binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headlamp-viewer
subjects:
  - kind: Group
    name: "ttttttttt"  # AzureViewer Group ID
    apiGroup: rbac.authorization.k8s.io

---
# viewer-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headlamp-viewer
rules:
  # Core API permissions
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/log"
      - "pods/exec"
      - "services"
      - "nodes"
      - "namespaces"
      - "configmaps"
      - "events"
      - "persistentvolumeclaims"
      - "persistentvolumes"
      - "serviceaccounts"
      - "endpoints"
      - "componentstatuses"
      - "resourcequotas"
      - "limitranges"
    verbs: ["get", "list", "watch"]

  # Metrics API permissions
  - apiGroups: ["metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

  # Apps API permissions
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "daemonsets"
      - "statefulsets"
      - "replicasets"
      - "controllerrevisions"
    verbs: ["get", "list", "watch"]

  # Batch API permissions
  - apiGroups: ["batch"]
    resources:
      - "jobs"
      - "cronjobs"
    verbs: ["get", "list", "watch"]

  # Networking API permissions
  - apiGroups: ["networking.k8s.io"]
    resources:
      - "ingresses"
      - "networkpolicies"
      - "ingressclasses"
    verbs: ["get", "list", "watch"]

  # RBAC permissions
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - "roles"
      - "rolebindings"
      - "clusterroles"
      - "clusterrolebindings"
    verbs: ["get", "list", "watch"]

  # Secrets permissions (restricted to specific namespace)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

  # Storage permissions
  - apiGroups: ["storage.k8s.io"]
    resources:
      - "storageclasses"
      - "volumeattachments"
    verbs: ["get", "list", "watch"]

  # Autoscaling permissions
  - apiGroups: ["autoscaling"]
    resources:
      - "horizontalpodautoscalers"
    verbs: ["get", "list", "watch"]

  # Custom Resource Definitions
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - "customresourcedefinitions"
    verbs: ["get", "list", "watch"]

  # Events
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

  # Flux permissions
  - apiGroups:
      - "source.toolkit.fluxcd.io"
      - "kustomize.toolkit.fluxcd.io"
      - "helm.toolkit.fluxcd.io"
      - "notification.toolkit.fluxcd.io"
      - "image.toolkit.fluxcd.io"
    resources:
      - "*"
    verbs: ["get", "list", "watch","patch"]

  # Self-subject access reviews (needed for UI to check permissions)
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - "selfsubjectaccessreviews"
      - "selfsubjectrulesreviews"
    verbs: ["create"]

  # Required for authentication validation (OIDC)
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - "tokenreviews"
      - "subjectaccessreviews"
    verbs: ["create"]

  # Coordination API (Leader Election)
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch"]
```
