### ISSUE TITLE
helm chart: documentation of extraManifests in values is wrong

### ISSUE THREAD

**Issue by dirk-olmes** [kubernetes-sigs/headlamp#3068]
The values file states that `extraManifests` can be added as YAML objects like this:
```
# -- Additional Kubernetes manifests to be deployed. Include the manifest as nested YAML.
extraManifests: []
# - apiVersion: v1
#   kind: ConfigMap
...
```

However when installing the helm chart with `extraManifests` structured as described, you get the error:
```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
headlamp:
- extraManifests.0: Invalid type. Expected: string, given: object
```

The correct syntax would be like this:
```
extraManifests:
  - |-
    apiVersion: v1
    kind: ConfigMap
...
```

Either the documentation should be updated or (preferably) the helm chart should respect the documented YAML structrure.

**Comment by eyeaadil** [comment]
@dirk-olmes Can you please specify how to generate this error? I want to work in this issue.

**Comment by dirk-olmes** [comment]
First, create a values file that looks like this: 
```
extraManifests:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: the-config-map
    data:
      foo: bar
```
Then, run `helm template --debug headlamp/headlamp --version 0.30.1 -f my-values.yaml`.
