### ISSUE TITLE
OIDC token refresh is not working

### ISSUE THREAD

**Issue by jrbushell** [kubernetes-sigs/headlamp#3143]
## Describe the bug
Running Headlamp in-cluster (kind), authenticating through a Keycloak OIDC server.

About 2 minutes after authentication (i.e. when the bearer token expires), a "Lost connection to the cluster" error is displayed, and the user is returned to the login dialog.

I checked the behaviour with the last few releases, and this seems to be a regression from 0.28.1 onwards. In 0.28.0, no error is seen, the user remains logged in, and it's possible to see the bearer token is getting refreshed.

## To Reproduce

With 0.28.0 (working)
- Log in through OIDC
- Wait 2 minutes
- No errors are seen, headlamp still works as expected
- Inspection of the bearer token for the healthz requests shows the exp time gets updated regularly

With 0.28.1 (failing; also 0.29.0, 0.30.0)
- Log in through OIDC
- Wait 2 minutes
- "Lost connection to the cluster" error is displayed
- Any further action redirects back to the login dialog

## Environment (please provide info about your environment):
 - Installation type: In-Cluster + Helm, in a Kind cluster
 - Headlamp Version: 0.28.1 onwards has the problem
 - Other: 

Helm chart values
```
config:
  extraArgs:
  - -insecure-ssl
  oidc:
    clientID: kube
    clientSecret: kube-client-secret
    issuerURL: https://oidc.kind.local:8443/realms/master
    scopes: email
env:
- name: SSL_CERT_DIR
  value: /cert
ingress:
  enabled: true
  hosts:
  - host: headlamp.ingress.kind.local
    paths:
    - path: /
      type: ImplementationSpecific
  ingressClassName: nginx
resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 50Mi
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
volumeMounts:
- mountPath: /cert
  name: cert
  readOnly: true
volumes:
- configMap:
    name: cert
  name: cert
```

## Are you able to fix this issue?
No.

## Additional Context
It was working correctly in 0.28.0
