### ISSUE TITLE
Headlamp in-cluster: exec to pods in clusters from static kubeconfig not working

### ISSUE THREAD

**Issue by mgalesloot** [kubernetes-sigs/headlamp#3214]
## Describe the bug
Headlamp in-cluster: exec or attach to pods in clusters from static kubeconfig is not working. 

## To Reproduce
Steps to reproduce the bug:
1. Install headlamp in-cluster with helm chart 
2. Provide a static kubeconfig with multiple clusters in the installaton, mounted from a configmap to /home/headlamp/.config/Headlamp/kubeconfigs/. e.g. 
```
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: <redacted>
      server: https://cluster1:6443
    name: cluster1
  - cluster:
      certificate-authority-data: <redacted>
      server: https://cluster1:6443
    name: cluster2
contexts:
  - context:
      cluster: cluster1
      user: cluster1
    name: cluster1
  - context:
      cluster: cluster2
      user: cluster2
    name: cluster2
current-context: ""
kind: Config
preferences: {}
users:
  - name: cluster1
    user:
      auth-provider:
        config:
          client-id: <redacted>.apps.googleusercontent.com
          client-secret: <redacted>
          idp-issuer-url: https://accounts.google.com
          scope: openid profile email
        name: oidc
  - name: cluster2
    user:
      auth-provider:
        config:
          client-id: <redacted>.apps.googleusercontent.com
          client-secret: <redacted>
          idp-issuer-url: https://accounts.google.com
          scope: openid profile email
        name: oidc

```
3. Observe
Login with OIDC and viewing of resources works well. Edit/ Delete works too. Nice! 

4. Exec/Attach From the UI
Try exec into a pod in another cluster, e.g. nginx controller
The frontend fails to connect. 
In the console, we see a wss call with exec, but there is no response. 
The same issue with exec. 
If we try exec into a pod in the main cluster, it works. But any other cluster fails. 

## Environment (please provide info about your environment):
 - Installation type: in-cluster 
 - Headlamp Version: 0.30 

## Are you able to fix this issue?
No. Of course I can help to test.
