### ISSUE TITLE
Port forward failed (spinner) when using kubecnfig with Pinniped

### ISSUE THREAD

**Issue by vhurtevent** [kubernetes-sigs/headlamp#3224]
## Describe the bug

We use Pinniped for Kubernetes authentication, and we use specific kubeconfig files crafted by Pinniped.

The user part of the kubeconfig use pinniped binary to authenticate user and looks like : 

```
users:
- name: user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - login
      - oidc
      - --enable-concierge
      - --concierge-api-group-suffix=pinniped.dev
      - --concierge-authenticator-name=supervisor-authenticator
      - --concierge-authenticator-type=jwt
      - --concierge-endpoint=https://cp.xxx.xxx:6443
      - --concierge-ca-bundle-data=LSxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
      - --issuer=https://pinniped.xxx.xxx/supervisor
      - --client-id=pinniped-cli
      - --scopes=offline_access,openid,pinniped:request-audience,username,groups
      - --request-audience=xxx-xxx-xxx
      - --upstream-identity-provider-name=Keycloak
      - --upstream-identity-provider-type=oidc
      - --upstream-identity-provider-flow=browser_authcode
      command: pinniped
      env: []
```

We can import and use Pinniped Kubeconfig in Headlamp, with no problem when browsing/edit/delete ressources, except for Port Forward.
When clicking on Port Forward button, the spinner loops for ever.
In the terminal where we launch Headlamp from, we can see logs like 

```
{"level":"error","clusterID":"xxxxxxxxxx","UserID":"4a9bd48814e3656c","source":"/home/runner/work/headlamp/headlamp/backend/cmd/multiplexer.go","line":508,"error":"dialing WebSocket: websocket: bad handshake","time":"2025-05-12T11:06:14+02:00","message":"establishing cluster connection"}
{"level":"error","clusterID":"xxxxxxxxxx","source":"/home/runner/work/headlamp/headlamp/backend/cmd/multiplexer.go","line":543,"time":"2025-05-12T11:06:14+02:00","message":"establishing cluster connection"}

server process stderr: {"level":"error","source":"/home/runner/work/headlamp/headlamp/backend/cmd/multiplexer.go","line":360,"error":"websocket: bad handshake","time":"2025-05-12T11:06:24+02:00","message":"dialing WebSocket"}
{"level":"error","source":"/home/runner/work/headlamp/headlamp/backend/cmd/multiplexer.go","line":361,"error":"marshaling error: json: unsupported type: func() (io.ReadCloser, error)","time":"2025-05-12T11:06:24+02:00","message":"WebSocket response"}
```

## To Reproduce
Steps to reproduce the bug:
1. Setup a Kubernetes cluster witth Pinniped autentication
2. Generate Pinniped kubeconfig file
3. Import Kubeconfig in Headlamp
4. Open a pod and Forward port

## Environment (please provide info about your environment):
 - Installation type: Debian Package
 - Headlamp Version: v0.30.0
 - Kubernetes : v1.31.8
 - Pinniped : v0.37.0
