### ISSUE TITLE
Missing OIDC Configuration Options for Azure Entra ID Integration

### ISSUE THREAD

**Issue by mihail-brinza** [kubernetes-sigs/headlamp#3380]
## Describe the bug

When deploying Headlamp on AKS with Azure Entra ID using the Helm chart, the deployment YAML is missing arguments and environment variables for `validatorClientID`, `validatorIssuerURL`, and `useAccessToken`, even though these are configured in the Helm values and the template appears to support them.
Docs used: [How to Set Up Headlamp on AKS with Azure Entra-ID as the OIDC provider](https://headlamp.dev/docs/latest/installation/in-cluster/azure-entra-id/)

## To Reproduce

1. Deploy Headlamp using Helm with these values:
   ```yaml
   serviceAccount:
     create: true
   clusterRoleBinding:
     create: true
   config:
     inCluster: true
     baseURL: '/headlamp'
     secret:
       create: true
     oidc:
       clientID: "your-client-id"
       clientSecret: "your-client-secret"
       issuerURL: "https://login.microsoftonline.com/tenant-id/v2.0"
       scopes: "6dae42f8-4368-4678-94ff-3960e28e3630/user.read openid email profile"
       validatorClientID: "6dae42f8-4368-4678-94ff-3960e28e3630"
       validatorIssuerURL: "https://sts.windows.net/tenant-id/"
       useAccessToken: true
   ```

2. Check the resulting deployment YAML
3. Notice that the deployment only includes basic OIDC arguments but missing validator and useAccessToken settings

## Environment:
- Installation type: Helm
- Headlamp Version: 0.30.1 (Chart version 0.30.1)
- Platform: Azure Kubernetes Service (AKS)
- Other: Microsoft Entra ID with Kubernetes RBAC enabled

## Actual Deployment

**deployment args (missing validator settings):**
```yaml
args:
  - '-in-cluster'
  - '-plugins-dir=/headlamp/plugins'
  - '-oidc-client-id=$(OIDC_CLIENT_ID)'
  - '-oidc-client-secret=$(OIDC_CLIENT_SECRET)'
  - '-oidc-idp-issuer-url=$(OIDC_ISSUER_URL)'
  - '-oidc-scopes=$(OIDC_SCOPES)'
  - '-base-url=/headlamp'
```

however, if I try to manually add them, the pod won't start because it doesn't know about these configuration, even though they seem to be referenced in the [deployment.yaml](https://github.com/kubernetes-sigs/headlamp/blob/main/charts/headlamp/templates/deployment.yaml) template of the helm chart.
```yaml
  - '-oidc-validator-client-id=$(OIDC_VALIDATOR_CLIENT_ID)'
  - '-oidc-validator-idp-issuer-url=$(OIDC_VALIDATOR_ISSUER_URL)'
  - '-oidc-use-access-token=$(OIDC_USE_ACCESS_TOKEN)'
```
Am I missing something here?

## Are you able to fix this issue?
No.

**Comment by illume** [comment]
Yes, sorry... there was a delay in that release so the docs were published for quite a long time before the release was done.

@mihail-brinza I wonder if the newer release is working for you? Or does this need investigation still?

**Comment by mihail-brinza** [comment]
I ended up using a oauth2proxy in front of it, and that worked, but I'll give it another try so I simply my infrastructure.

**Comment by nishasati6oct** [comment]
> I ended up using a oauth2proxy in front of it, and that worked, but I'll give it another try so I simply my infrastructure.

How did u use oauth2-proxy because for us its not at all working.

**Comment by mihail-brinza** [comment]
Here's roughly the setup I used (nginx ingress-nginx + cert-manager for TLS, oauth2-proxy in front, Headlamp's own ingress disabled).

**Headlamp Helm values** — no OIDC config here, ingress turned off:
```yaml
config:
  inCluster: true
  baseURL: /oauth2/headlamp
service:
  type: ClusterIP
ingress:
  enabled: false   # oauth2-proxy owns the public route, not headlamp
```

**oauth2-proxy Helm values** — this is the important part:
```yaml
replicaCount: 1

ingress:
  enabled: true
  className: nginx        # I'm using ingress-nginx as the controller
  hosts:
    - your.host.example.com
  path: /oauth2
  pathType: ImplementationSpecific
  tls:
    - secretName: headlamp-tls-secret
      hosts: [your.host.example.com]
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"

config:
  cookieSecret: <base64-encoded 32-byte secret>
  configFile: |
    email_domains = [ "*" ]

extraArgs:
  reverse-proxy: "true"          # required — you're behind ingress-nginx
  skip-provider-button: "true"
  cookie-refresh: "15m"
  cookie-expire: "12h"
  cookie-name: oauth2-proxy-headlamp
  cookie-domain: .your.host.example.com
  redirect-url: https://your.host.example.com/oauth2/callback
  proxy-prefix: /oauth2

alphaConfig:
  enabled: true              # v7+ alpha config, don't mix with the legacy --oidc-* flags
  configData:
    providers:
      - id: entra
        provider: oidc
        clientID: <azure-app-client-id>
        clientSecret: <azure-app-client-secret>
        scope: "<AKS-server-app-id>/user.read openid email profile User.Read"
        oidcConfig:
          issuerURL: https://login.microsoftonline.com/<tenant-id>/v2.0
          insecureAllowUnverifiedEmail: true
          emailClaim: email
          audienceClaims: ["aud"]
    injectRequestHeaders:      # this is what actually authenticates headlamp to the API server
      - name: Authorization
        values:
          - claim: access_token
            prefix: "Bearer "
    upstreamConfig:
      upstreams:
        - id: headlamp
          path: /oauth2/headlamp/
          uri: http://headlamp.headlamp.svc.cluster.local:80
          passHostHeader: true
          proxyWebSockets: true
```

A few things to keep in mind:
- `reverse-proxy: "true"` has to be set, otherwise oauth2-proxy doesn't trust the `X-Forwarded-*` headers from nginx ingress and redirect/cookie logic breaks.
- Once you turn on `alphaConfig`, you can't mix in the legacy `--oidc-issuer-url`/`--client-id` style args — it's one or the other.
- `injectRequestHeaders` is what actually gets Headlamp a usable bearer token — without it, Headlamp has no credentials to hit the Kubernetes API even though the login itself succeeds.
- Headlamp's own `ingress.enabled` must be `false`, or you'll get two ingress objects fighting over the same host/path.
- `redirect-url` / `cookie-domain` must exactly match the ingress host, and that redirect URI needs to be registered on the Azure AD app.
