### ISSUE TITLE
Unable to view logs or exec into pods

### ISSUE THREAD

**Issue by cian-sheehy** [kubernetes-sigs/headlamp#3401]
## Describe the bug
We have an in-cluster deployment of headlamp and we're unable to view logs or exec into pods

We are using OIDC, entra, AKS and oauthproxy. I was hoping to try this [document](https://headlamp.dev/docs/latest/installation/in-cluster/azure-entra-id/) to see if removing oauthproxy from the equation resolves the issue but that doesn't seem to work.

I have also tried this [document](https://headlamp.dev/docs/latest/installation/in-cluster/aks-cluster-oauth/) to but to no avail either. I will post my config below

## To Reproduce
Steps to reproduce the bug:
1. Login
2. Navigaet to any pod
3. Exec pod or view logs
4. Nothing happens. See screenshot

## Environment (please provide info about your environment):
 - Installation type: in-cluster (AKS)
 - Headlamp Version: v0.31.0

## Are you able to fix this issue?
No

## Additional Context

![Image](https://github.com/user-attachments/assets/a8669a38-a509-4d06-b4dc-0a0621a5098d)

headlamp deployment
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: headlamp-system
spec:
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      restartPolicy: Always
      volumes:
        - name: headlamp-plugins
          emptyDir: {}
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.31.0
          args:
            - "-in-cluster"
            - "-plugins-dir=/headlamp/plugins"
          ports:
            - containerPort: 4466
          securityContext:
            runAsUser: 100
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 4466
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: headlamp-plugins
              mountPath: /headlamp/plugins
          env:
            - name: HEADLAMP_CONFIG_OIDC_CLIENT_ID
              value: "${clientId}"
            - name: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
              value: "${clientSecret}"
            - name: HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL
              value: "https://login.microsoftonline.com/<tenant-id>/v2.0"
            - name: HEADLAMP_CONFIG_OIDC_SCOPES
              value: "6dae42f8-4368-4678-94ff-3960e28e3630/user.read openid profile email User.Read"
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 500Mi

      initContainers:
        - command:
            - /bin/sh
            - -c
            - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
          image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.2.0
          imagePullPolicy: Always
          name: headlamp-plugin-flux
          securityContext:
            runAsUser: 100
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /build/plugins
              name: headlamp-plugins
        - command:
            - /bin/sh
            - -c
            - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
          image: capitalontap.azurecr.io/headlamp-plugin:v1.0.1
          imagePullPolicy: Always
          name: headlamp-plugin
          securityContext:
            runAsUser: 100
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /build/plugins
              name: headlamp-plugins

```

oauth2-proxy helm releaes
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 120m
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  targetNamespace: headlamp-system
  interval: 60m
  timeout: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: oauth2-proxy
      version: 7.12.17
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    # Oauth client configuration specifics
    config:
      configFile: |-
        email_domains = [ "*" ]
    alphaConfig:
      enabled: true
      configData:
        providers:
          - id: entra
            provider: oidc
            clientID: ${clientId}
            clientSecret: ${clientSecret}
            scope: "6dae42f8-4368-4678-94ff-3960e28e3630/user.read openid profile email User.Read"
            oidcConfig:
              issuerURL: "https://login.microsoftonline.com/<tenant-id>/v2.0"
              insecureAllowUnverifiedEmail: true
              emailClaim: given_name
              audienceClaims:
                - aud
        injectRequestHeaders:
          - name: Authorization
            values:
              - claim: access_token
                prefix: "Bearer "
        upstreamConfig:
          upstreams:
            - id: main
              path: /
              uri: http://headlamp:80
              proxyWebSockets: true
    extraArgs:
      redirect-url: https://<ingress-host-name>/oauth2/callback
      reverse-proxy: true
      skip-provider-button: true
      silence-ping-logging: true
      cookie-expire: "60m"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi

```

ingress
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: headlamp
  namespace: headlamp-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.org/websocket-services: "headlamp,headlamp-system-oauth2-proxy"
spec:
  ingressClassName: nginx-int
  tls:
    - secretName: headlamp-general-tls
      hosts:
        - <host-name>
  rules:
    - host: <host-name>
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: headlamp-system-oauth2-proxy
                port:
                  number: 80

```
