### ISSUE TITLE
App Catalog - Web based support

### ISSUE THREAD

**Issue by vivekrsintc** [kubernetes-sigs/headlamp#3415]
## Is your feature request related to a problem? Please describe the impact that the lack of the feature requested is creating.
App Catalog plugin is one of key feature to discover and deploy the apps to cluster. Currently it has limitations that supports only on Desktop APP

## Describe the solution you'd like
It would be great if the APP Catalog plugin also enabled as web based and connect and manage the APP Catalog board from webAPP

## What users will benefit from this feature?
This becomes headlamp onestop solution for monitoring and deployment and management

## Are you able to implement this feature?
No, Im Currently learning the plugins. It would be great if anyone helps to understand how to convert the desktop feature to webbased
> Do you want to help implement this feature? Please see our [contribution docs](https://headlamp.dev/docs/latest/contributing). For any non-trivial contributions, we advise you to join our [our slack channel](https://kubernetes.slack.com/messages/headlamp) to discuss the implementation with Headlamp's core developers.

## Additional context
[If needed, add any other context or screenshots about the feature request here.]

**Comment by illume** [comment]
We have an option soon to allow the app-catalog to work on the web version deployed in cluster.

The service proxy pr.

**Comment by mlbiam** [comment]
Talking to @illume it sounds like this needs to get deployed to artifacthub.io in order to be available?  Also required for helm support to work.

**Comment by hollycai05** [comment]
Hi, I’d like to clarify the current support status of the app-catalog plugin in in-cluster (web) deployments.

In the latest release (0.8.0), is app-catalog expected to work when Headlamp is deployed in-cluster?

If yes, could you provide a minimal guide or reference steps for enabling it?

Here is what I tested:
* Headlamp deployed in-cluster via Helm
* latest 0.8.0 `app-catalog` plugin installed
* `-enable-helm` flag enabled

In **Settings → Plugins**, I can see app-catalog listed with status: `loaded`

However, the **App Catalog UI does not appear in the sidebar**.
My understanding is that the absence of a Helm controller/service should not affect plugin UI registration, only runtime functionality. So the plugin is still desktop-only or I missed sth?

Any clarification or example configuration would be very helpful. Thanks!

**Comment by bbourchanin** [comment]
Hi,

You are nearly done I think :

Did you add a catalog ? :
```
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: artifacthub-catalog
            namespace: headlamp
            labels:
              catalog.headlamp.dev/is-catalog: ''
            annotations:
              catalog.headlamp.dev/name: artifacthub-catalog
              catalog.headlamp.dev/protocol: artifacthub
              catalog.headlamp.dev/uri: https://artifacthub.io
          spec:
            type: ExternalName
            externalName: artifacthub.io
            ports:
              - name: https
                port: 443
                targetPort: 443
                protocol: TCP
```
My headlamp values :
```
          env:
            - name: https_proxy
              value: http://myproxy.com
            - name: no_proxy
              value: 127.0.0.0/8,10.0.0.0/8,.svc,.cluster.local, xxx
          config:
            pluginsDir: /build/plugins
            watchPlugins: true
            enableHelm: true
            oidc:
              clientID: keycloak-headlamp
              clientSecret: mysecret
              issuerURL: https://mykaycloak.com/realms/myrealm          
              scope: "profile,email,groups"
            extraArgs:
              - "-proxy-urls=https://artifacthub.io/*"
          initContainers:            
            - name: fetch-app-catalog
              image: alpine:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  export HTTPS_PROXY=http://myproxy.com
                  apk add npm git
                  git clone https://github.com/headlamp-k8s/plugins.git
                  cd plugins/app-catalog/
                  npm ci && npm run build && npm run package
                  cp package.json /headlamp/static-plugins/app-catalog/
                  cp dist/main.js /headlamp/static-plugins/app-catalog/
              volumeMounts:
              - name: plugin-catalog
                mountPath: /headlamp/static-plugins/app-catalog
          volumes:
            - name: plugin-catalog
              emptyDir: {}                         
          volumeMounts:
            - name: plugin-catalog
              mountPath: /headlamp/static-plugins/app-catalog
```
Once done i only have to do a F5 on my browser after connecting to headlamp
You can refer to : https://github.com/kubernetes-sigs/headlamp/issues/5066 for other elements

**Comment by bbourchanin** [comment]
For using multiple kubeconfigs for OIDC access to differents clusters ( https://headlamp.dev/docs/latest/installation/in-cluster/#use-a-non-default-kube-config-file ) I also had to mount a /home/headlamp/.config/helm to mitigate insufficient rights on the folder to make app-catalog working :
```
          volumes:          
            - name: headlamp-helminit
              emptyDir: {}
          volumeMounts:
            - name: headlamp-helminit
              mountPath: /home/headlamp/.config/helm

```
