### ISSUE TITLE
OIDC with ServiceAccount

### ISSUE THREAD

**Issue by LeeRoyManea** [kubernetes-sigs/headlamp#3441]
I want to give my Teams access to Headlamp. 

Headlamp is deployed like the following script
```yaml
kubectl -n kube-system create serviceaccount headlamp-admin
kubectl create clusterrolebinding headlamp-admin --serviceaccount=kube-system:headlamp-admin --clusterrole=cluster-admin

helm upgrade --install headlamp headlamp/headlamp \
  --namespace kube-system \
  --set "config.inCluster=true" \
  --set "serviceAccount.create=false" \
  --set "serviceAccount.name=headlamp-admin" \
  --set "config.oidc.clientID=${HEADLAMP_OIDC_CLIENT_ID}" \
  --set "config.oidc.clientSecret=${HEADLAMP_OIDC_CLIENT_SECRET}" \
  --set "config.oidc.issuerURL=${HEADLAMP_OIDC_ISSUER_URL}"
```

Is it possible to authorize the OIDC Users over the default Service account? 

Or is it possible to bypass the authentication complete and handle the access over the Reverse Proxy? 

After the login with OIDC i got the following exception. 

```
You don't have permissions to view this resource
- nodes.metrics.k8s.io is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "metrics.k8s.io" at the cluster scope
```

I have added a CRB with no effect 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-users-crb
  
subjects:
- kind: User
  name: leeroy.manea@multidigital.ch                
  apiGroup: rbac.authorization.k8s.io
  
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

Can someone tell me what is missing? 

i dont want to upload kubeconfig files.

**Comment by sw90lee** [comment]
Hello! Which OIDC provider are you currently integrating with? As far as I know, even when using OIDC, you still need to explicitly define ClusterRoles or Roles for the authenticated users.

In my setup, I'm using Keycloak. I've grouped user permissions into groups, and I've pre-applied Roles to these groups for simplified access management.

**Comment by LeeRoyManea** [comment]
I'm using Keycloak to.  

so on user level its not possible? 

```yaml
subjects:
- kind: User
  name: leeroy.manea@multidigital.ch                
  apiGroup: rbac.authorization.k8s.io
```

would you share this parts of your settings so i could adapt them?
