### ISSUE TITLE
Disable auto connect

### ISSUE THREAD

**Issue by 1oglop1** [kubernetes-sigs/headlamp#3476]
## Is your feature request related to a problem? Please describe the impact that the lack of the feature requested is creating.

When accessing multiple clusters headlamp tries to connect and either fails or succeeds. 
To access AWS EKS clusters I modified kubeconfig to use aws-vault
```
 user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - exec
          - my-profile
          - --region
          - eu-central-1
          - --
          - aws
          - eks
          - get-token
          - --cluster-name
          - services
          - --output
          - json
        command: aws-vault
```

When aws is configured with SSO, cli opens browser and prompts user to log in.
The problem is that with many clusters this opens many browsers and on top of it the retry logic keeps creating more login attempts and my browser ended up with 300 tabs while I was away.

## Describe the solution you'd like
I'd like to have a setting per cluster or a default behaviour to not connect to the cluster unless requested by the user.

## What users will benefit from this feature?

Every user who has modified kubeconfig to use [AWS Valut](https://github.com/99designs/aws-vault) or [Granted](https://docs.commonfate.io/granted/recipes/eks)

## Are you able to implement this feature?
 No. Sorry it would be too much for me at the moment.
> Do you want to help implement this feature? Please see our [contribution docs](https://headlamp.dev/docs/latest/contributing). For any non-trivial contributions, we advise you to join our [our slack channel](https://kubernetes.slack.com/messages/headlamp) to discuss the implementation with Headlamp's core developers.
