### ISSUE TITLE
app: minikube: runCmd: Add management script to allow list

### ISSUE THREAD

**Issue by illume** [kubernetes-sigs/headlamp#3507]
In order to run some other scripts to set up minikube (or other cluster software maybe) we need to do some other work.

- Ask user for permission to install HyperV
- Ask user to set up networking
- Ask user to restart their computer (current proposed solution requires this for linux/windows)
- ... Other system commands required to setup minikube on different platforms.

I was thinking a script that comes with the minikube plugin, which gets called by the app/. 
Then the electron app would ask the user if they want to use it, as the other commands. It could be ask every time... because these I think are only on install, not something they would use every day.

Note the commands will also probably have to ask for elevated permissions to do this stuff as well. For example on Windows, Windows itself will ask for permission on the Windows side before installing things that require admin privileges.

Some example commands:
```shell
minikube-manage-system.js ask-restart-windows
minikube-manage-system.js setup-hyperV-windows-networking
minikube-manage-system.js ask-restart-linux-ubuntu
```

### Benefits of keeping it with the minikube plugin

If the script is bundled with the minikube plugin it can be updated independently of the Headlamp app.

**Comment by illume** [comment]
We had that concept of the allowed commands being a service. So Headlamp could download a list of allowed commands from a github repo. So new plugins could add extra commands if they request. Then when people install a new plugin it could also fetch the new list of commands that are allowed to be run.

The benefit is it separates the allowed commands list update frequency from the release frequency of the Headlamp app.

**Comment by illume** [comment]
I think these are the two main things needed:

- Move that allow list stuff for commands to download from repo. (Currently we have it hardcoded in Headlamp to allow minikube from certain URLs)
- Allow scripts to be added to allow list, not just binaries.

**Comment by illume** [comment]
Here's the code that checks which binaries:
https://github.com/kubernetes-sigs/headlamp/blob/main/app/electron/runCmd.ts#L137-L148

Here's the check consent code:
https://github.com/kubernetes-sigs/headlamp/blob/main/app/electron/runCmd.ts#L96

Currently, we only allow downloads from github / minikube / release:
https://github.com/kubernetes-sigs/headlamp/blob/main/app/electron/plugin-management.ts#L849

**Comment by joaquimrocha** [comment]
Yeah. Opening the possibility of plugins shipping their own scripts that get executed in the users' machines would extend a possible attack surface. So just to make sure we are talking about the same, that list of commands that we download should be under our (Headlamp devs) control. If a plugin needs an extra command/tool/script in the list, they have to file a PR into our repo in order for us to review and eventually add it.

Summarizing:
1. We have a list of external tools, let's call it `hl-external-tools-VERSION-ARCH.yaml` available from our kubernetes-sigs/headlamp repo. A current copy is also shipped with Headlamp. VERSION is the file spec version (v1, v2, v3...) which can be helpful in the future. See a suggestion about the registry format at the bottom.
2. Headlamp has an "External Tools" settings page which shows a list of the available tools in the registry and what are already installed/available. This allows the user to control the external tools (install/remove manually), remove consent for them, etc.
3. Plugins should ask for tools to be run or installed. When attempting to run, if the tool is not installed but it's available, the Electron layer asks the user if they want to install it
4. Once it's available and the tool runs it, the Electron layer asks the user if they consent to giving access to that tool for (all) plugins to use

Would this work? Is there a simpler way to achieve this without having to trust plugins?

## Tools registry

This  `hl-external-tools-VERSION-ARCH.yaml`  holds a list of tools/commands/scripts we make available for plugins to run if they need it. E.g. (never mind the format, we should probably take ideas from existing formats like [flatpak's manifests](https://docs.flatpak.org/en/latest/manifests.html#modules)):
```yaml
tools:
  minikube:
    command: minikube
    version: v1.2.3
    url: https://download-url-for-minikube.example.com/minikube
    checksum: sha256:abcde
    type: binary
    skip-if:
    - command-exists: minikube
  vfkit-from-archive:
    url: https://download-url-for-minikube.example.com/vfkit.tar.gz
    type: archive
    checksum: sha256:abcde1
    script:
      name: install.sh
      code: |
        #/bin/sh
        install -m655 ...
  vfkit-from-brew:
    type: brew # Does check if brew is installed before running
    formula: vfkit
    args:
      - -something-something
  ensure-virtualization:
    type: script
    script:
      name: ensure-virt.sh
      code: |
        #/bin/sh
        if [ ! ... ]
```
